apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: redistore
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: dapr-redis-headless.dapr-tests.svc.cluster.local:6379
  - name: redisPassword
    value: ""
  - name: queryIndexes
    value: |
      [
        {
          "name": "userIndx",
          "indexes": [
            {
              "key": "person.org",
              "alias": "person_org",
              "type": "TEXT",
              "sortable": true
            },
            {
              "key": "person.id",
              "alias": "person_id",
              "type": "NUMERIC",
              "sortable": true
            },
            {
              "key": "city",
              "alias": "city",
              "type": "TEXT",
              "sortable": true
            },
            {
              "key": "state",
              "alias": "state",
              "type": "TEXT",
              "sortable": true
            }
          ]
        }
      ]
