apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: host
    value: "amqp://guest:guest@dapr-demo.default.svc.cluster.local:5672"
  - name: durable
    value: false
  - name: deletedWhenUnused
    value: "true"
