apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: dapr-demo-headless.default.svc.cluster.local:6379
  - name: redisPassword
    value: "guest"
  - name: consumerID
    value: "testConsumer"
  - name: processingTimeout
    value: 5s
  - name: redeliverInterval
    value: 1s
  - name: concurrency
    value: 1
