apiVersion: apps/v1
kind: Deployment
metadata:
  name: pub
  labels:
    app: pubsub-pub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pubsub-pub
  template:
    metadata:
      labels:
        app: pubsub-pub
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "pub"
    spec:
      containers:
      - name: pub
        image: docker.io/dmitsh/dapr-demo:0.1
        imagePullPolicy: Always
        command: ['/usr/local/bin/pub']
