apiVersion: apps/v1
kind: Deployment
metadata:
  name: pub
  labels:
    app: pubsub-pub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pubsub-pub
  template:
    metadata:
      labels:
        app: pubsub-pub
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "pub"
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8282"
    spec:
      containers:
      - name: pub
        image: docker.io/dmitsh/dapr-demo:0.1
        imagePullPolicy: Always
        command: ['/usr/local/bin/pub']
        ports:
        - name: prometheus
          containerPort: 8282
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
