apiVersion: apps/v1
kind: Deployment
metadata:
  name: pubsub
  labels:
    app: pubsub-pubsub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pubsub-pubsub
  template:
    metadata:
      labels:
        app: pubsub-pubsub
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "pubsub"
        dapr.io/app-port: "6100"
        dapr.io/log-level: "debug"
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: pub
        image: docker.io/dmitsh/dapr-demo:0.1
        imagePullPolicy: IfNotPresent
        command: ['/usr/local/bin/pub']
        args: ['-t', 'red', '-t', 'green', '-t', 'blue', '-m', '9091']
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      - name: sub
        image: docker.io/dmitsh/dapr-demo:0.1
        imagePullPolicy: IfNotPresent
        command: ['/usr/local/bin/sub']
        args: ['-t', 'red', '-t', 'green', '-t', 'blue', '-m', '9092']
        ports:
        - name: dapr
          containerPort: 6100
        - name: prom-pub
          containerPort: 9091
        - name: prom-sub
          containerPort: 9092
