apiVersion: apps/v1
kind: Deployment
metadata:
  name: pubsub
  labels:
    app: pubsub-pubsub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pubsub-pubsub
  template:
    metadata:
      labels:
        app: pubsub-pubsub
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "pubsub"
        dapr.io/app-port: "6100"
        dapr.io/log-level: "debug"
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9091"
    spec:
      containers:
      - name: pubsub
        image: docker.io/dmitsh/dapr-demo:0.1
        imagePullPolicy: Always
        command: ['/usr/local/bin/pubsub']
        args: ['-t', 'red', '-t', 'green', '-t', 'blue', '-m', '9091', '-d']
        ports:
        - name: dapr
          containerPort: 6100
        - name: prometheus
          containerPort: 9091
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
